version: "3.3"
networks:
   gamein:
     external: true
     
services:
  schedule:
    image: registry.dariasystem.com/gamein/schedule:dev
    container_name: schedule
    restart: always
    ports:
      - 8084:8080
    networks:
      - gamein
    environment:
      - spring.datasource.url=jdbc:postgresql://192.168.0.223:5432/gamein
      - spring.datasource.username=gamein
      - spring.datasource.password=gamein123
      - live.data.url=http://192.168.0.222:8083/websocket/api/notify
